services:
  mongodb:
      image: mongo:6
      container_name: blog-mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=oversix-gaming
    volumes:
      - './docker:/docker-entrypoint-initdb.d'

volumes:
  mongo-data: